### ISSUE TITLE
Support for parameter (i.e. ci=-1) for returning clientDomain-unspecific data

### ISSUE THREAD

**Issue by AydinChavez** [dtag-dev-sec/PEBA#35]
As spoken today, please additionally support returning alert-docs from ES without a clientDomain-filter.

From client/sicherheittacho perspective, this is only needed for the endpoints:
```
/alert/topCountriesAttacks
/alert/retrieveAlertStats
/alert/retrieveAlertsCountWithType
```

optional (can be done on client side as there is anyway some steps to do regarding flagging the origin for stuff like coloring etc):
```
/alert/retrieveAlertsJson
```

**Comment by vorband** [comment]
done in 0d2e0c0654bd4e08c9981ff457569e66e729fe17 

- added additional field "clientDomain" in /alert/retrieveAlertsJson
- added `ci=-1` option for 
```
/alert/topCountriesAttacks
/alert/retrieveAlertStats
/alert/retrieveAlertsCountWithType
```
