### ISSUE TITLE
Maxmind's GeoIP moved to GeoLite2

### ISSUE THREAD

**Issue by djeronimo** [dtag-dev-sec/PEBA#48]
Hi there,

In the the installation section of the MaxMind GeoIP the download.sh script no longer works.
# download Maxmind's GeoIP database and copy it to the right destination
cd var/lib/GeoIP/
./download.sh
sudo cp *.dat /var/lib/GeoIP/

Maxmind has moved to GeoLite2.
https://dev.maxmind.com/geoip/geoip2/geolite2/

Regards,
Danny

**Comment by vorband** [comment]
thank you and sorry for the late reply. apparently it's more than just exchanging the databases. I am currently looking into this and will fix it asap.

**Comment by vorband** [comment]
I have implemented it in the devbackup branch 47cb7f2 and will merge it into master as soon as I know it runs stable.
