### ISSUE TITLE
Create index on ES6

### ISSUE THREAD

**Issue by y0sh188** [dtag-dev-sec/PEBA#54]
Hi,

I deployed PEBA on ES6 and put the test data, but I could not put data to PEBA.
I found that there are some differences between "setup-es-indices.py" and "setupES6Indices.sh".

Do I need to update the script to use ES6?

**Comment by vorband** [comment]
You are right, the setupES6Indices.sh is currently not used in our setup, so there may be issues. You may want to update the script in order to reflect the changes in setup-es-indices.py.
